# Generated by Django 3.1 on 2020-08-07 05:14
import os

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations


def create_admin(apps, schema):
    get_user_model().objects.create_superuser(
        username=os.getenv('ADMIN_USERNAME', settings.ADMIN_USERNAME),
        password=os.getenv('ADMIN_PASSWORD', settings.ADMIN_PASSWORD)
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL)
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
