# Generated by Django 3.1 on 2020-08-06 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=1024, verbose_name='title')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, default=0, verbose_name='counter')),
                ('title', models.CharField(blank=True, default='', max_length=1024, verbose_name='title')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='order')),
                ('local', models.FileField(blank=True, null=True, upload_to='', verbose_name='local file')),
                ('remote', models.URLField(blank=True, null=True, verbose_name='remote URL')),
                ('local_subtitles', models.FileField(blank=True, null=True, upload_to='', verbose_name='local subtitles')),
                ('remote_subtitles', models.URLField(blank=True, null=True, verbose_name='subtitles URL')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', related_query_name='videos', to='content.page', verbose_name='page')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, default=0, verbose_name='counter')),
                ('title', models.CharField(blank=True, default='', max_length=1024, verbose_name='title')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='order')),
                ('original_text', models.TextField(verbose_name='original text')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', related_query_name='texts', to='content.page', verbose_name='page')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, default=0, verbose_name='counter')),
                ('title', models.CharField(blank=True, default='', max_length=1024, verbose_name='title')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='order')),
                ('local', models.FileField(blank=True, null=True, upload_to='', verbose_name='local file')),
                ('remote', models.URLField(blank=True, null=True, verbose_name='remote URL')),
                ('bitrate', models.IntegerField(verbose_name='bitrate')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios', related_query_name='audios', to='content.page', verbose_name='page')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
