# Generated by Django 3.1 on 2020-08-07 12:18

from django.db import migrations, models
import publisher.apps.content.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='local',
            field=models.FileField(blank=True, null=True, upload_to=publisher.apps.content.models.uploadable_content_path, verbose_name='local file'),
        ),
        migrations.AlterField(
            model_name='video',
            name='local',
            field=models.FileField(blank=True, null=True, upload_to=publisher.apps.content.models.uploadable_content_path, verbose_name='local file'),
        ),
        migrations.AlterField(
            model_name='video',
            name='local_subtitles',
            field=models.FileField(blank=True, null=True, upload_to=publisher.apps.content.models.uploadable_content_path, verbose_name='local subtitles'),
        ),
    ]
